### ISSUE TITLE
加载网页显示白屏的原因是什么，求助

### ISSUE THREAD

**Issue by dongdianyi** [hcanyz/ZJsBridge#1]

**Comment by hcanyz** [comment]
请提供一些基本信息
- url
- Webview
- 手机型号、系统版本

最好能提供demo : )

**Comment by dongdianyi** [comment]
> 
> 
> 请提供一些基本信息
> 
>     * url
> 
>     * Webview
> 
>     * 手机型号、系统版本
> 
> 
> 最好能提供demo : )

url是局域网的 http网址
BridgeWebView
华为10

**Comment by dongdianyi** [comment]
> 
> 
> > 请提供一些基本信息
> > ```
> > * url
> > 
> > * Webview
> > 
> > * 手机型号、系统版本
> > ```
> > 
> > 
> > 最好能提供demo : )
> 
> url是局域网的 http网址
> BridgeWebView
> 华为10

打包之后可以显示，debug模式下vue添加请求头去请求后台就是添加不上

**Comment by hcanyz** [comment]
> > > 请提供一些基本信息
> > > ```
> > > * url
> > > 
> > > * Webview
> > > 
> > > * 手机型号、系统版本
> > > ```
> > > 
> > > 
> > > 最好能提供demo : )
> > 
> > 
> > url是局域网的 http网址
> > BridgeWebView
> > 华为10
> 
> 打包之后可以显示，debug模式下vue添加请求头去请求后台就是添加不上

🤣 这个跟jsBridge没什么关系了。
问题可能性就比较多了，要看vue工程具体代码。
- 跨域了
- vue 代理转发配置问题
- url 的子域或者path不对
- ...

**Comment by dongdianyi** [comment]
> 
> 
> > > > 请提供一些基本信息
> > > > ```
> > > > * url
> > > > 
> > > > * Webview
> > > > 
> > > > * 手机型号、系统版本
> > > > ```
> > > > 
> > > > 
> > > > 最好能提供demo : )
> > > 
> > > 
> > > url是局域网的 http网址
> > > BridgeWebView
> > > 华为10
> > 
> > 
> > 打包之后可以显示，debug模式下vue添加请求头去请求后台就是添加不上
> 
> 🤣 这个跟jsBridge没什么关系了。
> 问题可能性就比较多了，要看vue工程具体代码。
> 
>     * 跨域了
> 
>     * vue 代理转发配置问题
> 
>     * url 的子域或者path不对
> 
>    
现在是华为手机可以显示  不过样式发生了变化，地图显示不正确
一加手机还是显示白屏

**Comment by hcanyz** [comment]
> > > > > 请提供一些基本信息
> > > > > ```
> > > > > * url
> > > > > 
> > > > > * Webview
> > > > > 
> > > > > * 手机型号、系统版本
> > > > > ```
> > > > > 
> > > > > 
> > > > > 最好能提供demo : )
> > > > 
> > > > 
> > > > url是局域网的 http网址
> > > > BridgeWebView
> > > > 华为10
> > > 
> > > 
> > > 打包之后可以显示，debug模式下vue添加请求头去请求后台就是添加不上
> > 
> > 
> > 🤣 这个跟jsBridge没什么关系了。
> > 问题可能性就比较多了，要看vue工程具体代码。
> > ```
> > * 跨域了
> > 
> > * vue 代理转发配置问题
> > 
> > * url 的子域或者path不对
> > ```
> 
> 现在是华为手机可以显示 不过样式发生了变化，地图显示不正确
> 一加手机还是显示白屏

有些手机能访问，这就是兼容问题了。可以使用 chrome://inspect/#devices 分析下。

**Comment by dongdianyi** [comment]
> 
> 
> > > > > > 请提供一些基本信息
> > > > > > ```
> > > > > > * url
> > > > > > 
> > > > > > * Webview
> > > > > > 
> > > > > > * 手机型号、系统版本
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > 最好能提供demo : )
> > > > > 
> > > > > 
> > > > > url是局域网的 http网址
> > > > > BridgeWebView
> > > > > 华为10
> > > > 
> > > > 
> > > > 打包之后可以显示，debug模式下vue添加请求头去请求后台就是添加不上
> > > 
> > > 
> > > 🤣 这个跟jsBridge没什么关系了。
> > > 问题可能性就比较多了，要看vue工程具体代码。
> > > ```
> > > * 跨域了
> > > 
> > > * vue 代理转发配置问题
> > > 
> > > * url 的子域或者path不对
> > > ```
> > 
> > 
> > 现在是华为手机可以显示 不过样式发生了变化，地图显示不正确
> > 一加手机还是显示白屏
> 
> 有些手机能访问，这就是兼容问题了。可以使用 chrome://inspect/#devices 分析下。

能加个联系方式吗

**Comment by hcanyz** [comment]
我加你吧。

**Comment by dongdianyi** [comment]
> 
> 
> 我加你吧。

qq:411913512
