### ISSUE TITLE
为什么将vue的代码部署到远端，choosePhotos返回的图片就无法在webview里展示了

### ISSUE THREAD

**Issue by phoenixsky** [hcanyz/ZJsBridge#2]
放在assets里本地加载是正常的
放在远端部署vue的项目，是不是有需要特别配置的地方。

**Comment by hcanyz** [comment]
能否提供一个最小复现的 demo , 和一些基础信息（webview版本、手机型号、系统版本）

初步怀疑是跨域了。
assets 跟 服务器部署，走的 uri scheme 不一样。 android 默认是不允许 http|https 访问 file 域文件的。需要通过 setAllowUniversalAccessFromFileURLs 开启访问权限。开启这个需要注意安全问题，防止被三方页面盗用。

**Comment by phoenixsky** [comment]
我这边直接用你的vue代码，部署起来和通过assets加载。返回图片地址 在前端展示 服务器部署的是不好用的。

**Comment by phoenixsky** [comment]
你那边部署的方式，图片可以正常展示么。如果只有我这不行的话，我晚些整个demo再试试。

**Comment by hcanyz** [comment]
我试了下是有这个问题
看下面日志，是被 android 拦截了。

```
"choosePhotos success, ret:[{"nativeResourceUrl":"content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FDCIM%2FCamera%2FIMG_20210331_220934.jpg"}]", source: http://192.168.43.27:8080/js/chunk-vendors.44073e36.js (17)

"Not allowed to load local resource: content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FDCIM%2FCamera%2FIMG_20210331_220934.jpg", source: http://192.168.43.27:8080/ (0)
```

**Comment by phoenixsky** [comment]
嗯，图片可能是要单独处理下了，不知道作者是否有此计划？

**Comment by hcanyz** [comment]
这个问题有时间我会研究下。

目前有俩种方式可以解决
- （推荐）使用 &lt;input type="file" /&gt;，android 端实现 onShowFileChooser
- 参考 https://github.com/hcanyz/ZJsBridge/commit/d39e964f1589c39f4686d8d50c0e3f7ed0215e70 ，使用虚拟资源的方式把文件传递给 javascript

**Comment by hcanyz** [comment]
https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader

可以试下这个，google 提供的本地资源共享方案。类似于项目中的 ”虚拟资源“

**Comment by phoenixsky** [comment]
感谢大佬，我研究下
